# Generated by Django 3.2.7 on 2021-09-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countermodel',
            name='number',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
