# Generated by Django 3.2.7 on 2021-09-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_alter_countermodel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countermodel',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
